# 异步和事件循环

## 1

```js
const promise = Promise.resolve().then(() => {
	return promise;
});
promise.catch(console.err);


// 答案
// [TypeError: Chaining cycle detected for promise #<Promise>]   
```

**.then 或 .catch 返回的值不能是 promise 本身，否则会造成死循环**

